#!/bin/ksh

pwd=$(pwd)
wd=$(basename ${pwd})
errorfnamepath="src/data/errors.log"

if [[ ${wd} != "parkit" ]]; then
    echo "You are working in: '${wd}'"
    echo "You need to be in:  'parkit'"
else
    for i in src/data src/appsrc/png src/appsrc/csv src/appsrc/gallery; do
        mkdir -p ${i}
    done

    if [[ ! -f ${errorfnamepath} ]]; then
        echo $(date) > ${errorfnamepath}
    fi
    /usr/bin/python3 src/ParkitWatchDog.py 2>${errorfnamepath}
fi
